import React from 'react';
import { promises as fs } from 'fs';
import path from 'path';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { materialDark } from 'react-syntax-highlighter/dist/esm/styles/prism';

// This component serves as a comprehensive gallery of our simulation work.
// It first presents the core Python scripts that drive our emulators, providing
// a transparent view into the logic of our "Code as Proof" methodology.
// Below the code, a full gallery of generated visualizations (plots and GIFs)
// offers a visual testament to the outcomes of our various computational experiments.

interface ScriptData {
  title: string;
  content: string;
}

const EthernetSequenceDisplay = async () => {
  // --- Data Definition ---
  // A definitive list of the core Python scripts for our emulators.
  const scriptPaths = [
    { title: 'Test Ethernet', path: 'scripts/ethernet/test_ethernet.py' },
    { title: 'Log Visualizer v1', path: 'scripts/ethernet/log_visualizer.py' },
    { title: 'Log Visualizer v2', path: 'scripts/ethernet/log_visualizer_2.py' },
    { title: 'Log Visualizer v3', path: 'scripts/ethernet/log_visualizer_3.py' },
    { title: 'Headless Simulation Runner', path: 'scripts/ethernet/run_headless_sim.py' },
  ];

  // A comprehensive list of all visualization artifacts generated by our emulators.
  // This list is curated to represent the breadth of our research, from protocol
  // analysis to network topology visualizations.

  // A comprehensive list of all visualization artifacts generated by our emulators.
  // This list is curated to represent the breadth of our research, from protocol
  // analysis to network topology visualizations.
  const imageUrls = [
    "/scripts/ethernet-sequence/comprehensive3.py_ethernet_contention.gif",
    "/scripts/ethernet-sequence/comprehensive4.gif",
    "/scripts/ethernet-sequence/network_topology.png",
    "/scripts/ethernet-sequence/packet_spraying.png",
    "/scripts/ethernet/ethernet-21-2.png",
    "/scripts/ethernet/ethernet14-1.png",
    "/scripts/ethernet/ethernet15-1.png",
    "/scripts/ethernet/ethernet21-1.png",
    "/scripts/ethernet/ethernet25-1.png",
    "/scripts/ethernet/ethernet25-2.png",
    "/scripts/ethernet/ethernet6-1.png",
    "/scripts/ethernet/ethernet6-2.png",
    "/scripts/ethernet/gif_files/BufferBloat MetcalfeFull.gif",
    "/scripts/ethernet/gif_files/active building.gif",
    "/scripts/ethernet/gif_files/aloha heavy pure.gif",
    "/scripts/ethernet/gif_files/automotive tsn.gif",
    "/scripts/ethernet/gif_files/baseline fibre.gif",
    "/scripts/ethernet/gif_files/credit starvation fibre.gif",
    "/scripts/ethernet/gif_files/csma aloha moderate.gif",
    "/scripts/ethernet/gif_files/csma:cd aloha heavy.gif",
    "/scripts/ethernet/gif_files/daedaelus fabric .gif",
    "/scripts/ethernet/gif_files/daedaelus-large-fabric-initialization.gif",
    "/scripts/ethernet/gif_files/efficiency vs packet size metcalfe half duplex.gif",
    "/scripts/ethernet/gif_files/metcalfe half duplex high contention & collision storm.gif",
    "/scripts/ethernet/gif_files/metcalfe-low-contention.gif",
    "/scripts/ethernet/gif_files/multi-flow-congestion.gif",
    "/scripts/ethernet/gif_files/multiflow contention on fabric fibre.gif",
    "/scripts/ethernet/gif_files/pure aloha moderate.gif",
    "/scripts/ethernet/gif_files/single flow baseline full.gif",
    "/scripts/ethernet/gif_files/slotted aloha moderate.gif",
    "/scripts/ethernet/gif_files/slotted heavy aloha.gif",
    "/scripts/ethernet/gif_files/small-tile-daedaelus.gif",
    "/scripts/ethernet/gif_files/tcp handshake fd.gif",
    "/scripts/ethernet/gif_files/tcp handshake hd contention.gif",
    "/scripts/ethernet/gif_files/tcp handshake hd no contention.gif",
    "/scripts/ethernet/plots/active_building/plot_log_20250622_150604.png",
    "/scripts/ethernet/plots/active_building/plot_log_20250622_150621.png",
    "/scripts/ethernet/plots/active_building/plot_log_20250622_210349.png",
    "/scripts/ethernet/plots/active_building/plot_log_20250622_210409.png",
    "/scripts/ethernet/plots/active_building/plot_log_20250622_210423.png",
    "/scripts/ethernet/plots/active_building/signal_sine_log_20250622_150604.png",
    "/scripts/ethernet/plots/active_building/signal_sine_log_20250622_150621.png",
    "/scripts/ethernet/plots/active_building/signal_sine_log_20250622_210349.png",
    "/scripts/ethernet/plots/active_building/signal_sine_log_20250622_210409.png",
    "/scripts/ethernet/plots/active_building/signal_sine_log_20250622_210423.png",
    "/scripts/ethernet/plots/active_building/signal_triangle_log_20250622_150604.png",
    "/scripts/ethernet/plots/active_building/signal_triangle_log_20250622_150621.png",
    "/scripts/ethernet/plots/active_building/signal_triangle_log_20250622_210349.png",
    "/scripts/ethernet/plots/active_building/signal_triangle_log_20250622_210409.png",
    "/scripts/ethernet/plots/active_building/signal_triangle_log_20250622_210423.png",
    "/scripts/ethernet/plots/active_building/spraying_log_20250622_150604.png",
    "/scripts/ethernet/plots/active_building/spraying_log_20250622_150621.png",
    "/scripts/ethernet/plots/active_building/spraying_log_20250622_210349.png",
    "/scripts/ethernet/plots/active_building/spraying_log_20250622_210409.png",
    "/scripts/ethernet/plots/active_building/spraying_log_20250622_210423.png",
    "/scripts/ethernet/plots/active_building/topology_log_20250622_150604.png",
    "/scripts/ethernet/plots/active_building/topology_log_20250622_150621.png",
    "/scripts/ethernet/plots/active_building/topology_log_20250622_210349.png",
    "/scripts/ethernet/plots/active_building/topology_log_20250622_210409.png",
    "/scripts/ethernet/plots/active_building/topology_log_20250622_210423.png",
    "/scripts/ethernet/plots/automotive_tsn/fitness_analysis_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/fitness_analysis_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/plot_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/plot_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_analysis_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_analysis_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_sine_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_sine_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_triangle_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/signal_triangle_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/spraying_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/spraying_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/topology_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/topology_log_20250622_210201.png",
    "/scripts/ethernet/plots/automotive_tsn/variance_analysis_log_20250622_150517.png",
    "/scripts/ethernet/plots/automotive_tsn/variance_analysis_log_20250622_210201.png",
    "/scripts/ethernet/plots/csmacd_aloha/contention_Heavy_Load_2s_log_20250622_205331.gif",
    "/scripts/ethernet/plots/csmacd_aloha/contention_Moderate_Load_log_20250622_205620.gif",
    "/scripts/ethernet/plots/csmacd_aloha/contention_log_20250622_150346.gif",
    "/scripts/ethernet/plots/csmacd_aloha/fitness_analysis_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/fitness_analysis_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/fitness_analysis_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/plot_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/plot_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/plot_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_analysis_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_analysis_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_analysis_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_sine_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_sine_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_sine_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_triangle_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_triangle_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/signal_triangle_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/spraying_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/spraying_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/spraying_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/topology_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/topology_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/topology_log_20250622_150346.png",
    "/scripts/ethernet/plots/csmacd_aloha/variance_analysis_Heavy_Load_2s_log_20250622_205331.png",
    "/scripts/ethernet/plots/csmacd_aloha/variance_analysis_Moderate_Load_log_20250622_205620.png",
    "/scripts/ethernet/plots/csmacd_aloha/variance_analysis_log_20250622_150346.png",
    "/scripts/ethernet/plots/daedaelus_fabric/acknowledged_Large_Fabric_Initialization_log_20250622_202421.gif",
    "/scripts/ethernet/plots/daedaelus_fabric/acknowledged_Small_Tile_Formation_log_20250622_202335.gif",
    "/scripts/ethernet/plots/daedaelus_fabric/acknowledged_log_20250622_150509.gif",
    "/scripts/ethernet/plots/daedaelus_fabric/acknowledged_log_20250622_210130.gif",
    "/scripts/ethernet/plots/daedaelus_fabric/plot_Large_Fabric_Initialization_log_20250622_202421.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/plot_Small_Tile_Formation_log_20250622_202335.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/plot_log_20250622_150509.jpg",
    // "/scripts/ethernet/plots/daedaelus_fabric/plot_log_20250622_150509.png",
    "/scripts/ethernet/plots/daedaelus_fabric/plot_log_20250622_210130.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_sine_Large_Fabric_Initialization_log_20250622_202421.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_sine_Small_Tile_Formation_log_20250622_202335.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_sine_log_20250622_150509.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_sine_log_20250622_210130.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_triangle_Large_Fabric_Initialization_log_20250622_202421.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_triangle_Small_Tile_Formation_log_20250622_202335.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_triangle_log_20250622_150509.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/signal_triangle_log_20250622_210130.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/spraying_Large_Fabric_Initialization_log_20250622_202421.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/spraying_Small_Tile_Formation_log_20250622_202335.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/spraying_log_20250622_150509.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/spraying_log_20250622_210130.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/topology_Large_Fabric_Initialization_log_20250622_202421.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/topology_Small_Tile_Formation_log_20250622_202335.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/topology_log_20250622_150509.jpg",
    "/scripts/ethernet/plots/daedaelus_fabric/topology_log_20250622_210130.jpg",
    "/scripts/ethernet/plots/fibre_channel_stretch/acknowledged_Baseline_Performance_log_20250622_201708.gif",
    "/scripts/ethernet/plots/fibre_channel_stretch/acknowledged_Credit_Starvation_log_20250622_201809.gif",
    "/scripts/ethernet/plots/fibre_channel_stretch/acknowledged_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.gif",
    "/scripts/ethernet/plots/fibre_channel_stretch/acknowledged_log_20250622_145114.gif",
    "/scripts/ethernet/plots/fibre_channel_stretch/acknowledged_log_20250622_150128.gif",
    "/scripts/ethernet/plots/fibre_channel_stretch/plot_Baseline_Performance_log_20250622_201708.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/plot_Credit_Starvation_log_20250622_201809.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/plot_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/plot_log_20250622_145114.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/plot_log_20250622_150128.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_sine_Baseline_Performance_log_20250622_201708.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_sine_Credit_Starvation_log_20250622_201809.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_sine_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_sine_log_20250622_145114.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_sine_log_20250622_150128.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_triangle_Baseline_Performance_log_20250622_201708.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_triangle_Credit_Starvation_log_20250622_201809.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_triangle_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_triangle_log_20250622_145114.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/signal_triangle_log_20250622_150128.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/spraying_Baseline_Performance_log_20250622_201708.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/spraying_Credit_Starvation_log_20250622_201809.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/spraying_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/spraying_log_20250622_145114.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/spraying_log_20250622_150128.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/topology_Baseline_Performance_log_20250622_201708.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/topology_Credit_Starvation_log_20250622_201809.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/topology_Multi-Flow_Contention_on_Fabric_Fibre_log_20250622_201943.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/topology_log_20250622_145114.png",
    "/scripts/ethernet/plots/fibre_channel_stretch/topology_log_20250622_150128.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/acknowledged_log_20250622_150501.gif",
    "/scripts/ethernet/plots/fullduplex_ethernet/fitness_analysis_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/plot_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/signal_analysis_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/signal_sine_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/signal_triangle_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/spraying_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/topology_log_20250622_150501.png",
    "/scripts/ethernet/plots/fullduplex_ethernet/variance_analysis_log_20250622_150501.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/acknowledged_log_20250622_150444.gif",
    "/scripts/ethernet/plots/halfduplex_ethernet/fitness_analysis_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/plot_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/signal_analysis_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/signal_sine_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/signal_triangle_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/spraying_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/topology_log_20250622_150444.png",
    "/scripts/ethernet/plots/halfduplex_ethernet/variance_analysis_log_20250622_150444.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/acknowledged_Bufferbloat_Scenario_log_20250622_205901.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/acknowledged_Multi_Flow_Congestion_log_20250622_205817.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/acknowledged_Single_Flow_Baseline_log_20250622_205740.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/acknowledged_log_20250622_145124.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/acknowledged_log_20250622_150137.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/contention_Bufferbloat_Scenario_log_20250622_205901.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/contention_log_20250622_145124.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/contention_log_20250622_150137.gif",
    "/scripts/ethernet/plots/metcalfe_fullduplex/plot_Bufferbloat_Scenario_log_20250622_205901.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/plot_Multi_Flow_Congestion_log_20250622_205817.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/plot_Single_Flow_Baseline_log_20250622_205740.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/plot_log_20250622_145124.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/plot_log_20250622_150137.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_sine_Bufferbloat_Scenario_log_20250622_205901.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_sine_Multi_Flow_Congestion_log_20250622_205817.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_sine_Single_Flow_Baseline_log_20250622_205740.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_sine_log_20250622_145124.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_sine_log_20250622_150137.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_triangle_Bufferbloat_Scenario_log_20250622_205901.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_triangle_Multi_Flow_Congestion_log_20250622_205817.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_triangle_Single_Flow_Baseline_log_20250622_205740.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_triangle_log_20250622_145124.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/signal_triangle_log_20250622_150137.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/spraying_Bufferbloat_Scenario_log_20250622_205901.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/spraying_Multi_Flow_Congestion_log_20250622_205817.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/spraying_Single_Flow_Baseline_log_20250622_205740.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/spraying_log_20250622_145124.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/spraying_log_20250622_150137.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/topology_Bufferbloat_Scenario_log_20250622_205901.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/topology_Multi_Flow_Congestion_log_20250622_205817.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/topology_Single_Flow_Baseline_log_20250622_205740.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/topology_log_20250622_145124.png",
    "/scripts/ethernet/plots/metcalfe_fullduplex/topology_log_20250622_150137.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/acknowledged_Efficiency_vs_Packet_size_log_20250622_203209.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/acknowledged_High_Contention_&_Collision_Storm_log_20250622_202833.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/acknowledged_Low_Contention_log_20250622_202710.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/acknowledged_log_20250622_150228.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/acknowledged_log_20250622_150232.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/contention_Efficiency_vs_Packet_size_log_20250622_203209.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/contention_High_Contention_&_Collision_Storm_log_20250622_202833.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/contention_Low_Contention_log_20250622_202710.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/contention_log_20250622_150228.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/contention_log_20250622_150232.gif",
    "/scripts/ethernet/plots/metcalfe_halfduplex/fitness_analysis_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/fitness_analysis_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/fitness_analysis_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/fitness_analysis_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/fitness_analysis_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/plot_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/plot_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/plot_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/plot_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/plot_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_analysis_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_analysis_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_analysis_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_analysis_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_analysis_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_sine_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_sine_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_sine_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_sine_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_sine_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_triangle_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_triangle_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_triangle_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_triangle_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/signal_triangle_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/spraying_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/spraying_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/spraying_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/spraying_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/spraying_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/topology_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/topology_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/topology_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/topology_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/topology_log_20250622_150232.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/variance_analysis_Efficiency_vs_Packet_size_log_20250622_203209.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/variance_analysis_High_Contention_&_Collision_Storm_log_20250622_202833.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/variance_analysis_Low_Contention_log_20250622_202710.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/variance_analysis_log_20250622_150228.png",
    "/scripts/ethernet/plots/metcalfe_halfduplex/variance_analysis_log_20250622_150232.png",
    "/scripts/ethernet/plots/plot_log_04f85ea7f00647d9b6a2aadc6ac6e5f8.png",
    "/scripts/ethernet/plots/plot_log_768917df54064fd0985f00427e85a53d.png",
    "/scripts/ethernet/plots/protocol_multidimensional_analysis.png",
    "/scripts/ethernet/plots/pure_aloha/contention_Heavy_Load_2_seconds_log_20250622_204558.gif",
    "/scripts/ethernet/plots/pure_aloha/contention_Heavy_Load_log_20250622_204033.gif",
    "/scripts/ethernet/plots/pure_aloha/contention_Moderate_Load_log_20250622_205530.gif",
    "/scripts/ethernet/plots/pure_aloha/contention_log_20250622_150401.gif",
    "/scripts/ethernet/plots/pure_aloha/fitness_analysis_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/fitness_analysis_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/fitness_analysis_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/fitness_analysis_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/plot_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/plot_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/plot_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/plot_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/signal_analysis_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/signal_analysis_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/signal_analysis_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/signal_analysis_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/signal_sine_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/signal_sine_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/signal_sine_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/signal_sine_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/signal_triangle_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/signal_triangle_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/signal_triangle_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/signal_triangle_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/spraying_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/spraying_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/spraying_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/spraying_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/topology_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/topology_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/topology_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/topology_log_20250622_150401.png",
    "/scripts/ethernet/plots/pure_aloha/variance_analysis_Heavy_Load_2_seconds_log_20250622_204558.png",
    "/scripts/ethernet/plots/pure_aloha/variance_analysis_Heavy_Load_log_20250622_204033.png",
    "/scripts/ethernet/plots/pure_aloha/variance_analysis_Moderate_Load_log_20250622_205530.png",
    "/scripts/ethernet/plots/pure_aloha/variance_analysis_log_20250622_150401.png",
    "/scripts/ethernet/plots/slotted_aloha/contention_Heavy_Load_2s_log_20250622_204828.gif",
    "/scripts/ethernet/plots/slotted_aloha/contention_Moderate_Load_log_20250622_205553.gif",
    "/scripts/ethernet/plots/slotted_aloha/contention_log_20250622_150424.gif",
    "/scripts/ethernet/plots/slotted_aloha/fitness_analysis_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/fitness_analysis_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/fitness_analysis_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/plot_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/plot_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/plot_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_analysis_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_analysis_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_analysis_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_sine_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_sine_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_sine_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_triangle_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_triangle_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/signal_triangle_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/spraying_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/spraying_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/spraying_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/topology_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/topology_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/topology_log_20250622_150424.png",
    "/scripts/ethernet/plots/slotted_aloha/variance_analysis_Heavy_Load_2s_log_20250622_204828.png",
    "/scripts/ethernet/plots/slotted_aloha/variance_analysis_Moderate_Load_log_20250622_205553.png",
    "/scripts/ethernet/plots/slotted_aloha/variance_analysis_log_20250622_150424.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/acknowledged_log_20250622_150321.gif",
    "/scripts/ethernet/plots/tcp_handshake_fd/acknowledged_log_20250622_210058.gif",
    "/scripts/ethernet/plots/tcp_handshake_fd/fitness_analysis_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/fitness_analysis_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/plot_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/plot_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_analysis_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_analysis_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_sine_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_sine_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_triangle_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/signal_triangle_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/spraying_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/spraying_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/topology_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/topology_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/variance_analysis_log_20250622_150321.png",
    "/scripts/ethernet/plots/tcp_handshake_fd/variance_analysis_log_20250622_210058.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/acknowledged_log_20250622_150255.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/acknowledged_log_20250622_210033.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/contention_log_20250622_150255.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/contention_log_20250622_210033.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/fitness_analysis_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/fitness_analysis_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/plot_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/plot_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_analysis_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_analysis_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_sine_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_sine_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_triangle_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/signal_triangle_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/spraying_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/spraying_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/topology_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/topology_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/variance_analysis_log_20250622_150255.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_contention/variance_analysis_log_20250622_210033.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/acknowledged_log_20250622_150238.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/acknowledged_log_20250622_210004.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/acknowledged_log_20250622_210014.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/contention_log_20250622_150238.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/contention_log_20250622_210004.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/contention_log_20250622_210014.gif",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/fitness_analysis_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/fitness_analysis_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/fitness_analysis_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/plot_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/plot_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/plot_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_analysis_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_analysis_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_analysis_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_sine_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_sine_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_sine_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_triangle_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_triangle_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/signal_triangle_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/spraying_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/spraying_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/spraying_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/topology_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/topology_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/topology_log_20250622_210014.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/variance_analysis_log_20250622_150238.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/variance_analysis_log_20250622_210004.png",
    "/scripts/ethernet/plots/tcp_handshake_hd_no_contention/variance_analysis_log_20250622_210014.png",
    "/scripts/ethernet/plots/plot_log_04f85ea7f00647d9b6a2aadc6ac6e5f8.png",
    "/scripts/ethernet/plots/plot_log_768917df54064fd0985f00427e85a53d.png",
    "/scripts/ethernet/plots/protocol_multidimensional_analysis.png",
    "/scripts/ethernet/plots/throughput_vs_load_summary.png",
    "/scripts/ethernet/plots/throughput_vs_load_unknown.png"
  ];


  // Asynchronously read the content of each script from the filesystem.
  // This operation is performed at build time on the server.
  const scripts: ScriptData[] = await Promise.all(
    scriptPaths.map(async (script) => {
      const filePath = path.join(process.cwd(), 'public', script.path);
      try {
        const content = await fs.readFile(filePath, 'utf-8');
        return { title: script.title, content };
      } catch (error) {
        console.error(`Error reading script ${script.path}:`, error);
        return { title: script.title, content: `# ERROR: Could not load script.` };
      }
    })
  );

  return (
    <div className="python-model-container">
      {/* --- Section 1: Python Emulator Scripts --- */}
      <section className="mb-16">
        <h2 className="text-3xl font-bold text-gray-200 mb-6 border-b border-gray-700 pb-3">
          Core Emulator Scripts
        </h2>
        <div className="space-y-8">
          {scripts.map((script, index) => (
            <div key={index} className="model-code-container">
              <h3 className="model-code-title">{script.title}</h3>
              <SyntaxHighlighter
                language="python"
                style={materialDark}
                wrapLongLines={true}
                customStyle={{
                  margin: 0,
                  borderRadius: 0,
                  backgroundColor: 'transparent',
                  padding: '1rem 1.25rem',
                }}
              >
                {script.content.trim()}
              </SyntaxHighlighter>
            </div>
          ))}
        </div>
      </section>

      {/* --- Section 2: Image Gallery --- */}
      <section>
        <h2 className="text-3xl font-bold text-gray-200 mb-6 border-b border-gray-700 pb-3">
          Visualization Gallery
        </h2>
        {/* <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {imageUrls.map((url, index) => (
            <div key={index} className="bg-gray-800 p-2 rounded-lg border border-gray-700">
              <img
                src={url}
                alt={`Simulation Visualization ${index + 1}`}
                className="w-full h-auto rounded-md"
                loading="lazy"
              />
            </div>
          ))}
        </div> */}
        {/* Masonry layout --------------------------------------------------- */}
        {/*  - `columns-*` sets the column count at each breakpoint
            - `break-inside-avoid-column` keeps every card whole
            - `mb-4` adds vertical gutter               */}
        <div className="columns-2 sm:columns-3 md:columns-4 lg:columns-5 gap-4 [column-fill:_balance]">
          {imageUrls.map((url, index) => (
            <div
              key={index}
              className="break-inside-avoid-column mb-4 bg-gray-800 p-2 rounded-lg border border-gray-700"
            >
              <img
                src={url}
                alt={`Simulation Visualization ${index + 1}`}
                className="w-full h-auto rounded-md"
                loading="lazy"
              />
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default EthernetSequenceDisplay;