import xml.etree.ElementTree as ET
import time
import collections
import random
from typing import List, Dict, Any, Optional

# This script serves as a Python-based emulator for the core logic of the
# SignalsAndGateways project. It embodies the Daedaelus philosophy by creating a
# computational model of a system where network logic is not hardcoded but
# dynamically configured. The goal is to provide a clear, executable
# representation of how routing, transformation, and buffering rules, defined
# in external configurations, govern the flow of information through a gateway,
# bridging disparate network technologies like CAN and Ethernet.

# --- Configuration Data ---
# To make this a single, self-contained file, the XML configurations are
# stored as strings. In a real system, these would be separate .xml files.

GATEWAY_CONFIG_XML = """
<config>
    <gateway id="gateway1">
        <routing>
            <route source="0" destination="1">
                <canframe canId="1"/>
                <canframe canId="2"/>
                <canframe canId="3"/>
            </route>
        </routing>
        <buffering>
            <pool>
                <holdup time="5ms">
                    <canframe canId="1"/>
                </holdup>
                <holdup time="10ms">
                    <canframe canId="2"/>
                </holdup>
            </pool>
        </buffering>
        <transformation destination="1" type="toEthernet">
            <ethernetframe dst="0A-00-00-00-00-04">
                <canframe canId="1"/>
                <canframe canId="2"/>
                <canframe canId="3"/>
            </ethernetframe>
        </transformation>
    </gateway>

    <gateway id="gateway2">
        <routing>
            <route source="1" destination="0">
                <ethernetframe dst="0A-00-00-00-00-04"/>
            </route>
        </routing>
        <transformation destination="0" type="toCan">
            <ethernetframe dst="0A-00-00-00-00-04"/>
        </transformation>
    </gateway>
</config>
"""

# --- Core Classes: Representing Packets and Network Entities ---

class Packet:
    """
    The base representation of a unit of information flowing through the network.
    Every message, regardless of its protocol, is a packet with a source,
    a set of potential destinations, and a unique identity.
    """
    def __init__(self, name: str, source_port: int, payload: Any = None):
        self.name = name
        self.source_port = source_port
        self.payload = payload
        self.timestamp = time.time()
        self.destination_ports: List[int] = []

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', from={self.source_port}, to={self.destination_ports})"

class CanFrame(Packet):
    """
    Represents a CAN frame, a fundamental message type on a bus network.
    It is identified by its canId, which determines its priority and content.
    In our model, these are the indivisible tokens of information generated by sensors.
    """
    def __init__(self, can_id: int, source_port: int, data: str):
        super().__init__(name=f"CAN_0x{can_id:X}", source_port=source_port, payload=data)
        self.can_id = can_id

    def get_identifier(self) -> str:
        return f"can_{self.can_id}"

class EthernetFrame(Packet):
    """
    Represents an Ethernet frame for the high-speed backbone.
    Its primary job is to carry a payload, which is often a 'GatewayAggregationMessage'
    containing multiple, smaller CAN frames. This is a practical application of our
    Graph Virtual Machine concept, where we create a logical container to manage a
    set of related information units.
    """
    def __init__(self, dest_mac: str, source_port: int, payload: Any):
        super().__init__(name=f"ETH_to_{dest_mac}", source_port=source_port, payload=payload)
        self.dest_mac = dest_mac

    def get_identifier(self) -> str:
        return f"eth_{self.dest_mac}"

class GatewayAggregationMessage(Packet):
    """
    A logical container used to group multiple UnitMessages (CAN frames) for transport
    within a single Ethernet frame. This aggregation is key to achieving efficiency,
    turning many small, high-overhead messages into one larger, efficient packet for
    the backbone network, without losing the individual identity of the constituent tokens.
    """
    def __init__(self, source_port: int, units: List[CanFrame]):
        super().__init__(name="GW_Aggregation", source_port=source_port, payload=units)
        self.units = units

    def __repr__(self) -> str:
        return f"GatewayAggregationMessage(units={len(self.units)})"

class PoolMessage(Packet):
    """
    A message used internally by the buffering module to signal that a pool of
    CAN frames is ready for transformation after its hold-up time has expired.
    """
    def __init__(self, source_port: int, can_frames: List[CanFrame]):
        super().__init__(name="PoolMessage", source_port=source_port, payload=can_frames)

# --- Logic Modules: Decoupling Gateway Functionality ---

class GatewayConfig:
    """
    Parses the gateway's XML configuration file. This embodies the principle of
    separating policy (the 'what', defined in XML) from mechanism (the 'how',
    implemented in code). The gateway's behavior is defined by this external
    ruleset, not by its implementation.
    """
    def __init__(self, xml_string: str):
        self.routing_rules = collections.defaultdict(dict)
        self.transformation_rules = {}
        self.buffering_rules = collections.defaultdict(dict)
        self._parse_config(xml_string)

    def _parse_config(self, xml_string: str):
        root = ET.fromstring(xml_string)
        for gateway in root.findall('gateway'):
            gid = gateway.get('id')
            self._parse_routing(gid, gateway.find('routing'))
            self._parse_transformation(gid, gateway.findall('transformation'))
            self._parse_buffering(gid, gateway.find('buffering'))

    def _parse_routing(self, gid: str, routing_element: Optional[ET.Element]):
        if routing_element is None:
            return
        for route in routing_element.findall('route'):
            src = int(route.get('source'))
            dest = int(route.get('destination'))
            rules = []
            for frame in route:
                if frame.tag == 'canframe':
                    rules.append(f"can_{frame.get('canId')}")
                elif frame.tag == 'ethernetframe':
                    rules.append(f"eth_{frame.get('dst')}")
            self.routing_rules[gid][(src, dest)] = rules

    def _parse_transformation(self, gid: str, transform_elements: List[ET.Element]):
        for trans in transform_elements:
            dest = int(trans.get('destination'))
            ttype = trans.get('type')
            rules = []
            for frame in trans:
                if frame.tag == 'ethernetframe':
                    can_ids = [int(cf.get('canId')) for cf in frame.findall('canframe')]
                    rules.append({'type': 'ethernet', 'dst': frame.get('dst'), 'can_ids': can_ids})
                elif frame.tag == 'canframe':
                    rules.append({'type': 'can'})
            self.transformation_rules[(gid, dest, ttype)] = rules

    def _parse_buffering(self, gid: str, buffering_element: Optional[ET.Element]):
        if buffering_element is None:
            return
        for pool in buffering_element.findall('pool'):
            for holdup in pool.findall('holdup'):
                hold_time_str = holdup.get('time') # e.g., "5ms"
                hold_time = float(hold_time_str.replace('ms', '')) / 1000.0
                for canframe in holdup.findall('canframe'):
                    can_id = int(canframe.get('canId'))
                    self.buffering_rules[gid][can_id] = {'pool_id': id(pool), 'hold_time': hold_time}

class GatewayRouter:
    """
    Decides message forwarding based on the parsed routing rules. It acts as
    the first gatekeeper, ensuring that only valid and intended data flows
    cross network boundaries.
    """
    def __init__(self, config: GatewayConfig, gateway_id: str):
        self.config = config
        self.gateway_id = gateway_id

    def process(self, packet: Packet) -> Packet:
        """Determines destination ports for a packet."""
        destinations = set()
        for (src, dest), rules in self.config.routing_rules.get(self.gateway_id, {}).items():
            if src == packet.source_port and hasattr(packet, 'get_identifier') and packet.get_identifier() in rules:
                destinations.add(dest)
        packet.destination_ports = list(destinations)
        return packet

class AccumulationGatewayBuffering:
    """
    This module buffers incoming frames and groups them according to the XML
    configuration. This is a computational model of the 'holdup' mechanism, where
    we trade a small amount of latency for a large gain in network efficiency
    by aggregating frames.
    """
    def __init__(self, config: GatewayConfig, gateway_id: str, simulation):
        self.config = config
        self.gateway_id = gateway_id
        self.pools = collections.defaultdict(list)
        self.pool_timers = {}
        self.simulation = simulation # To access simulation time

    def process(self, packet: Packet) -> Optional[Packet]:
        """Buffers CAN frames or passes other packets through."""
        if not isinstance(packet, CanFrame):
            return packet

        buffering_rule = self.config.buffering_rules.get(self.gateway_id, {}).get(packet.can_id)
        if not buffering_rule:
            return packet # This CAN frame is not part of any pool

        pool_id = buffering_rule['pool_id']
        hold_time = buffering_rule['hold_time']
        self.pools[pool_id].append(packet)

        # If this is the first packet for this pool, start the timer.
        if pool_id not in self.pool_timers or self.pool_timers[pool_id] is None:
            release_time = self.simulation.current_time + hold_time
            self.pool_timers[pool_id] = release_time
            print(f"    [Buffer] Pool {pool_id} started. Releasing at {release_time:.3f}s.")

        return None # Packet is buffered

    def check_timers(self) -> List[PoolMessage]:
        """Called each simulation tick to check if any pools should be released."""
        ready_pools = []
        for pool_id, release_time in list(self.pool_timers.items()):
            if release_time is not None and self.simulation.current_time >= release_time:
                frames_to_release = self.pools.pop(pool_id)
                self.pool_timers[pool_id] = None # Reset timer
                if frames_to_release:
                    print(f"    [Buffer] Pool {pool_id} released with {len(frames_to_release)} frames.")
                    # Source port is arbitrary here as it's an internal message
                    ready_pools.append(PoolMessage(source_port=-1, can_frames=frames_to_release))
        return ready_pools

class GatewayTransformation:
    """
    Transforms packets from one protocol to another, performing the crucial work of
    encapsulation and de-encapsulation. This module makes inter-network
    communication possible, acting as a universal translator.
    """
    def __init__(self, config: GatewayConfig, gateway_id: str):
        self.config = config
        self.gateway_id = gateway_id

    def process(self, packet: Packet) -> List[Packet]:
        """Transforms a packet based on its type and destination."""
        if isinstance(packet, PoolMessage):
            # A pool of CAN frames needs to be aggregated into an Ethernet frame.
            can_frames = packet.payload
            dest_port = packet.destination_ports[0] # Assume pool goes to one ethernet port
            rules = self.config.transformation_rules.get((self.gateway_id, dest_port, 'toEthernet'), [])
            if rules:
                rule = rules[0] # Assume one rule for simplicity
                dest_mac = rule['dst']
                agg_msg = GatewayAggregationMessage(source_port=dest_port, units=can_frames)
                eth_frame = EthernetFrame(dest_mac=dest_mac, source_port=dest_port, payload=agg_msg)
                eth_frame.destination_ports = [dest_port]
                return [eth_frame]

        elif isinstance(packet, CanFrame):
            # A single CAN frame to be transformed.
            dest_port = packet.destination_ports[0]
            rules = self.config.transformation_rules.get((self.gateway_id, dest_port, 'toEthernet'), [])
            if rules:
                rule = rules[0]
                dest_mac = rule['dst']
                agg_msg = GatewayAggregationMessage(source_port=dest_port, units=[packet])
                eth_frame = EthernetFrame(dest_mac=dest_mac, source_port=dest_port, payload=agg_msg)
                eth_frame.destination_ports = [dest_port]
                return [eth_frame]

        elif isinstance(packet, EthernetFrame):
             # An Ethernet frame needs to be de-encapsulated into CAN frames.
             dest_port = packet.destination_ports[0]
             rules = self.config.transformation_rules.get((self.gateway_id, dest_port, 'toCan'), [])
             if rules and isinstance(packet.payload, GatewayAggregationMessage):
                 can_frames = packet.payload.units
                 for frame in can_frames:
                     frame.destination_ports = [dest_port]
                 return can_frames

        return [packet] # No transformation needed


class Gateway:
    """
    The central component that connects networks. It orchestrates the flow of
    packets through its internal logic modules: router, bufferer, and transformer.
    Its behavior is entirely dictated by its loaded configuration.
    """
    def __init__(self, gateway_id: str, config: GatewayConfig, simulation):
        self.id = gateway_id
        self.router = GatewayRouter(config, gateway_id)
        self.bufferer = AccumulationGatewayBuffering(config, gateway_id, simulation)
        self.transformer = GatewayTransformation(config, gateway_id)
        self.ports: Dict[int, Any] = {} # Maps port number to connected entity
        print(f"Gateway '{self.id}' created. This entity is the lynchpin, applying configured rulesets to bridge communication domains.")

    def connect(self, port: int, target: Any):
        """Connects a gateway port to another network entity."""
        self.ports[port] = target

    def receive(self, packet: Packet):
        """Main entry point for a packet arriving at the gateway."""
        print(f"[GW {self.id}] Received: {packet.name} on port {packet.source_port}")

        # 1. Routing: Determine where the packet is allowed to go.
        routed_packet = self.router.process(packet)
        if not routed_packet.destination_ports:
            print(f"    [Router] Packet {packet.name} dropped, no valid route found.")
            return
        print(f"    [Router] Packet {packet.name} routed to port(s) {routed_packet.destination_ports}")

        # 2. Buffering: Hold the packet if it's part of an aggregation pool.
        buffered_packet = self.bufferer.process(routed_packet)
        if buffered_packet is None:
            print(f"    [Buffer] Packet {packet.name} is being held in a pool.")
            return

        # 3. Transformation: Convert the packet format if necessary.
        transformed_packets = self.transformer.process(buffered_packet)
        for p in transformed_packets:
            print(f"    [Transform] Packet transformed to: {p.name}")
            self._send(p)

    def check_and_send_buffered_packets(self):
        """Method to be called on each simulation tick to release buffered packets."""
        ready_pools = self.bufferer.check_timers()
        for pool_msg in ready_pools:
            # Route the pooled message
            routed_pool = self.router.process(pool_msg.payload[0]) # Route based on first packet
            if routed_pool.destination_ports:
                pool_msg.destination_ports = routed_pool.destination_ports
                transformed_packets = self.transformer.process(pool_msg)
                for p in transformed_packets:
                    print(f"    [Transform] Pooled message transformed to: {p.name}")
                    self._send(p)

    def _send(self, packet: Packet):
        """Forwards the packet to its destination ports."""
        for dest_port in packet.destination_ports:
            if dest_port in self.ports:
                target = self.ports[dest_port]
                # The packet's new source port becomes the gateway port it's leaving from.
                packet.source_port = dest_port
                print(f"[GW {self.id}] Sending: {packet.name} out of port {dest_port}")
                target.receive(packet)
            else:
                print(f"[GW {self.id}] Warning: Destination port {dest_port} not connected.")


class EndNode:
    """Represents a source or sink of data, like a sensor or an ECU."""
    def __init__(self, name: str, network_connection: Gateway, port: int):
        self.name = name
        self.network = network_connection
        self.port = port
        self.network.connect(port, self)
        print(f"EndNode '{self.name}' created and connected to port {self.port}.")

    def send(self, packet: Packet):
        print(f"[Node {self.name}] Sending: {packet.name}")
        self.network.receive(packet)

    def receive(self, packet: Packet):
        print(f"[Node {self.name}] Received: {packet.name} with payload: {packet.payload}")


class CanTrafficSource(EndNode):
    """A node that periodically generates CAN frames."""
    def __init__(self, name: str, network_connection: Gateway, port: int):
        super().__init__(name, network_connection, port)
        self.frames_to_send = []

    def add_frame_schedule(self, can_id: int, data: str, interval: float, start_delay: float = 0):
        self.frames_to_send.append({
            'can_id': can_id, 'data': data, 'interval': interval,
            'next_send_time': start_delay
        })

    def tick(self, current_time: float):
        for schedule in self.frames_to_send:
            if current_time >= schedule['next_send_time']:
                can_frame = CanFrame(can_id=schedule['can_id'], source_port=self.port, data=schedule['data'])
                self.send(can_frame)
                schedule['next_send_time'] = current_time + schedule['interval']


class Simulation:
    """
    The main simulation engine. It orchestrates the entire process, stepping
    through time and triggering events, modeling the flow of information through
    our Graph Virtual Machine.
    """
    def __init__(self, config_xml: str):
        print("--- Initializing Daedaelus Simulation Environment ---")
        self.config = GatewayConfig(config_xml)
        self.current_time = 0.0
        # The physical setup is modeled by instantiating gateways and nodes
        self.gateway1 = Gateway("gateway1", self.config, self)
        self.gateway2 = Gateway("gateway2", self.config, self)

        # Create the nodes and connect them to the gateways
        # This mirrors the physical topology of a multi-domain system
        self.can_node_1 = CanTrafficSource("CAN_Node_1", self.gateway1, port=0)
        self.ethernet_switch = self._create_switch() # A simplified switch
        self.can_node_2 = EndNode("CAN_Node_2", self.gateway2, port=0)

        # Connect the gateways to each other via the "Ethernet backbone"
        self.gateway1.connect(port=1, target=self.ethernet_switch)
        self.gateway2.connect(port=1, target=self.ethernet_switch)
        print("--- Network Topology Constructed ---")


    def _create_switch(self):
        """A simple switch model that forwards frames between gateways."""
        switch = collections.namedtuple('Switch', ['receive'])
        def receive(packet: EthernetFrame):
            print(f"[Switch] Received {packet.name}, forwarding...")
            # Simple logic: if from gw1, send to gw2, and vice-versa
            if packet.source_port == self.gateway1.ports[1]: # from gateway1
                self.gateway2.receive(packet)
            else: # from gateway2
                self.gateway1.receive(packet)
        return switch(receive)

    def run(self, duration: float, tick_step: float = 0.001):
        """Runs the simulation for a given duration."""
        print(f"\n--- Running Simulation for {duration} seconds ---")
        end_time = self.current_time + duration
        while self.current_time < end_time:
            print(f"\n--- Tick {self.current_time:.3f}s ---")
            # Trigger source nodes to generate traffic
            self.can_node_1.tick(self.current_time)

            # Allow gateways to process their buffered messages
            self.gateway1.check_and_send_buffered_packets()
            self.gateway2.check_and_send_buffered_packets()

            time.sleep(0.05) # Slow down for readability
            self.current_time += tick_step
        print("\n--- Simulation Complete ---")


if __name__ == "__main__":
    # This is where we define the experiment. We instantiate the simulation
    # environment with our ruleset and define the traffic patterns.
    sim = Simulation(GATEWAY_CONFIG_XML)

    # Schedule traffic generation from our CAN source node
    # This mimics sensors reporting data at different frequencies.
    # CAN ID 1 will be buffered with a 5ms hold-up.
    sim.can_node_1.add_frame_schedule(can_id=1, data="temp:22.5C", interval=0.020)
    # CAN ID 2 will be buffered with a 10ms hold-up.
    sim.can_node_1.add_frame_schedule(can_id=2, data="speed:100kph", interval=0.030)
    # CAN ID 3 is routed and transformed but not buffered.
    sim.can_node_1.add_frame_schedule(can_id=3, data="status:OK", interval=0.050)

    # Run the simulation loop
    sim.run(duration=0.1)