#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Daedaelus Log Visualizer - Automated Directory Traversal
---------------------------------------------------------
Creates comprehensive visualizations from all simulation log files found
within a specified directory structure. This script is designed to parse the
JSON logs generated by test_ethernet.py and produce multiple artifacts for each log:
  - A static PNG image with 5 summary plots.
  - An animated GIF of a basic Ethernet contention simulation.
  - An animated GIF of a reliable, acknowledged protocol simulation.

Usage:
  python log_visualizer.py [path/to/logs/directory]
"""

import json
import argparse
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import os
import simpy
import random
import math
import imageio
import pygame
import sys
import collections

# --- Contention Simulation Components ---


class ContentionConfig:
    SIM_DURATION_S = 0.05
    RANDOM_SEED = 42
    PROPAGATION_SPEED_M_S = 2e8
    ETHER_LENGTH_M = 500
    JAM_SIGNAL_BITS = 32
    SCREEN_WIDTH, SCREEN_HEIGHT = 800, 300
    STATION_COLOR, IDLE_COLOR = (200, 200, 200), (100, 100, 255)
    TRANSMIT_COLOR, COLLISION_COLOR, JAM_COLOR = (
        100, 255, 100), (255, 100, 100), (255, 150, 50)
    PACKET_HEIGHT = 15


class ContentionPacket:
    def __init__(self, source_id): self.source_id = source_id


class ContentionEther:
    def __init__(self, env):
        self.env = env
        self.transmitting_stations = {}
        self.is_jammed = False

    def is_busy(self): return bool(self.transmitting_stations)
    def has_collision(self): return len(self.transmitting_stations) > 1


class ContentionStation:
    def __init__(self, env, station_id, ether, params, viz):
        self.env, self.id, self.ether, self.params, self.viz = env, station_id, ether, params, viz
        self.packet_queue = simpy.Store(env)
        self.collisions = 0
        self.env.process(self.packet_generator())
        self.env.process(self.run())

    def packet_generator(self):
        for _ in range(3):
            yield self.env.timeout(random.expovariate(1.0 / self.params['mean_arrival_s']))
            yield self.packet_queue.put(ContentionPacket(self.id))
            if self.viz:
                self.viz.update_station_state(self.id, 'queued')

    def run(self):
        while True:
            pkt = yield self.packet_queue.get()
            if self.viz:
                self.viz.update_station_state(self.id, 'queued')
            yield self.env.process(self.transmit(pkt))

    def transmit(self, pkt):
        while True:
            if not self.ether.is_busy():
                if self.viz:
                    self.viz.update_station_state(self.id, 'transmitting')
                self.ether.transmitting_stations[self.id] = self.env.now
                yield self.env.timeout(self.params['propagation_delay_s'])
                if self.ether.has_collision():
                    if self.viz:
                        self.viz.update_station_state(self.id, 'collision')
                    del self.ether.transmitting_stations[self.id]
                    yield self.env.process(self.handle_collision(pkt))
                    break
                yield self.env.timeout(self.params['packet_tx_time_s'] - self.params['propagation_delay_s'])
                del self.ether.transmitting_stations[self.id]
                self.collisions = 0
                if self.viz:
                    self.viz.update_station_state(self.id, 'idle')
                break
            else:
                if self.viz:
                    self.viz.update_station_state(self.id, 'deferring')
                yield self.env.timeout(self.params['slot_time_s'])

    def handle_collision(self, pkt):
        self.collisions += 1
        self.ether.is_jammed = True
        if self.viz:
            self.viz.trigger_jam()
        yield self.env.timeout(self.params['jam_tx_time_s'])
        self.ether.is_jammed = False
        slots = random.randint(0, (2 ** min(self.collisions, 10)) - 1)
        backoff = slots * self.params['slot_time_s']
        if self.viz:
            self.viz.update_station_state(self.id, f'backoff {slots}')
        if backoff > 0:
            yield self.env.timeout(backoff)
        yield self.packet_queue.put(pkt)


class ContentionVisualizer:
    def __init__(self, num_stations, protocol_name):
        pygame.init()
        self.screen = pygame.display.set_mode(
            (ContentionConfig.SCREEN_WIDTH, ContentionConfig.SCREEN_HEIGHT))
        pygame.display.set_caption(f'Daedaelus Contention: {protocol_name}')
        self.font = pygame.font.Font(None, 20)
        self.station_positions = {i: (int(ContentionConfig.SCREEN_WIDTH * (i + 1) / (
            num_stations + 1)), ContentionConfig.SCREEN_HEIGHT // 2) for i in range(num_stations)}
        self.station_states = {i: {
            'state': 'idle', 'color': ContentionConfig.IDLE_COLOR} for i in range(num_stations)}
        self.jam_animation = 0
        self.frames = []

    def trigger_jam(self): self.jam_animation = 10

    def update_station_state(self, sid, state):
        cmap = {'idle': ContentionConfig.IDLE_COLOR, 'queued': (
            255, 255, 100), 'transmitting': ContentionConfig.TRANSMIT_COLOR, 'collision': ContentionConfig.COLLISION_COLOR, 'deferring': (100, 180, 255)}
        self.station_states[sid]['state'] = state
        self.station_states[sid]['color'] = cmap.get(state, (200, 0, 200))

    def draw(self, env, ether):
        self.screen.fill((10, 20, 30))
        y = ContentionConfig.SCREEN_HEIGHT // 2
        col = ContentionConfig.IDLE_COLOR
        if ether.is_jammed or self.jam_animation > 0:
            col, self.jam_animation = ContentionConfig.JAM_COLOR, self.jam_animation - 1
        elif ether.has_collision():
            col = ContentionConfig.COLLISION_COLOR
        elif ether.is_busy():
            col = ContentionConfig.TRANSMIT_COLOR
        pygame.draw.line(self.screen, col, (50, y),
                         (ContentionConfig.SCREEN_WIDTH - 50, y), 5)
        for i, pos in self.station_positions.items():
            s = self.station_states[i]
            pygame.draw.circle(
                self.screen, ContentionConfig.STATION_COLOR, pos, 12)
            pygame.draw.circle(self.screen, s['color'], pos, 10)
            pygame.draw.line(
                self.screen, ContentionConfig.STATION_COLOR, pos, (pos[0], pos[1]-12), 2)
            id_txt, state_txt = self.font.render(f"S{i}", True, (255, 255, 255)), self.font.render(
                s['state'].split()[0], True, s['color'])
            self.screen.blit(id_txt, (pos[0]-id_txt.get_width()//2, pos[1]+15))
            self.screen.blit(
                state_txt, (pos[0]-state_txt.get_width()//2, pos[1]+30))
        for sid, start in ether.transmitting_stations.items():
            x0 = self.station_positions[sid][0]
            prog = min((env.now - start) * ContentionConfig.PROPAGATION_SPEED_M_S /
                       ContentionConfig.ETHER_LENGTH_M, 1.0)
            w = prog * (ContentionConfig.SCREEN_WIDTH - 100) / 2
            pygame.draw.rect(self.screen, col, pygame.Rect(
                x0-w, y-ContentionConfig.PACKET_HEIGHT/2, w, ContentionConfig.PACKET_HEIGHT), border_radius=3)
            pygame.draw.rect(self.screen, col, pygame.Rect(
                x0, y-ContentionConfig.PACKET_HEIGHT/2, w, ContentionConfig.PACKET_HEIGHT), border_radius=3)
        self.screen.blit(self.font.render(
            f"Time: {env.now:.6f}s", True, (255, 255, 255)), (10, 10))
        pygame.display.flip()
        self.frames.append(pygame.surfarray.array3d(
            self.screen).transpose((1, 0, 2)))

    def save_gif(self, filename, fps=30): imageio.mimsave(
        filename, self.frames, fps=fps, loop=0); pygame.quit()

# --- Acknowledged Protocol Simulation Components ---


class AckSimConfig:
    SIM_DURATION_S, RANDOM_SEED = 2.0, 42
    TOTAL_DATA_PACKETS = 10
    RETRANSMISSION_TIMEOUT_S = 0.05
    ETHER_LENGTH_M, PROPAGATION_SPEED_M_S, ETHER_SPEED_BPS = 500, 2e8, 3e6
    DATA_PACKET_BITS, ACK_PACKET_BITS, JAM_SIGNAL_BITS = 4096, 256, 32
    MEAN_BACKGROUND_ARRIVAL_S = 100.0
    SCREEN_WIDTH, SCREEN_HEIGHT = 1000, 400
    DATA_COLOR, ACK_COLOR = (100, 255, 100), (100, 200, 255)
    PACKET_HEIGHT = 15
    STATION_COLOR, IDLE_COLOR = (200, 200, 200), (100, 100, 255)
    COLLISION_COLOR, JAM_COLOR = (255, 100, 100), (255, 150, 50)

    @staticmethod
    def get_params():
        p = {}
        p['propagation_delay_s'] = AckSimConfig.ETHER_LENGTH_M / \
            AckSimConfig.PROPAGATION_SPEED_M_S
        p['slot_time_s'] = 2 * p['propagation_delay_s']
        p['data_tx_time_s'] = AckSimConfig.DATA_PACKET_BITS / \
            AckSimConfig.ETHER_SPEED_BPS
        p['ack_tx_time_s'] = AckSimConfig.ACK_PACKET_BITS / \
            AckSimConfig.ETHER_SPEED_BPS
        p['jam_tx_time_s'] = AckSimConfig.JAM_SIGNAL_BITS / \
            AckSimConfig.ETHER_SPEED_BPS
        return p


class AckPacket:
    def __init__(self, ptype, seq, ack, src, dst):
        self.ptype, self.seq_num, self.ack_num = ptype, seq, ack
        self.source_id, self.destination_id = src, dst
        self.color = AckSimConfig.DATA_COLOR if ptype == 'DATA' else AckSimConfig.ACK_COLOR


class AckEther:
    def __init__(self, env):
        self.env = env
        self.transmitting_stations = {}
        self.is_jammed = False
        self.pipes = {}

    def is_busy(self): return bool(self.transmitting_stations)
    def has_collision(self): return len(self.transmitting_stations) > 1

    def broadcast(self, sender_id, packet):
        for sid, pipe in self.pipes.items():
            if sid != sender_id:
                pipe.put(packet)


class AckStation:
    def __init__(self, env, station_id, ether, params, stats, viz):
        self.env, self.id, self.ether, self.params, self.stats, self.viz = env, station_id, ether, params, stats, viz
        self.is_sender = (station_id == params['sender_id'])
        self.is_receiver = (station_id == params['receiver_id'])
        self.packet_queue = simpy.Store(env)
        self.collisions = 0
        if self.is_sender:
            self.unacked_seq = -1
            self.retx_proc = None
        if self.is_receiver:
            self.expected_seq_num = 0
        env.process(self.packet_generator())
        env.process(self.receiver_logic())
        env.process(self.sender_logic())

    def packet_generator(self):
        if self.is_sender:
            for i in range(AckSimConfig.TOTAL_DATA_PACKETS):
                yield self.packet_queue.put(AckPacket('DATA', i, -1, self.id, self.params['receiver_id']))
        else:
            while True:
                yield self.env.timeout(random.expovariate(1.0/AckSimConfig.MEAN_BACKGROUND_ARRIVAL_S))
                dest = random.choice(
                    [i for i in range(self.params['num_stations']) if i != self.id])
                yield self.packet_queue.put(AckPacket('DATA', -1, -1, self.id, dest))

    def receiver_logic(self):
        pipe = self.ether.pipes[self.id]
        while True:
            pkt = yield pipe.get()
            if self.is_receiver and pkt.ptype == 'DATA' and pkt.destination_id == self.id:
                if pkt.seq_num == self.expected_seq_num:
                    self.stats['app_packets_received'] += 1
                    self.expected_seq_num += 1
                yield self.packet_queue.put(AckPacket('ACK', -1, pkt.seq_num, self.id, pkt.source_id))
            if self.is_sender and pkt.ptype == 'ACK' and pkt.destination_id == self.id:
                if pkt.ack_num == self.unacked_seq:
                    self.stats['acks_received'] += 1
                    if self.retx_proc and not self.retx_proc.triggered:
                        self.retx_proc.interrupt()
                    self.unacked_seq = -1

    def sender_logic(self):
        while True:
            if self.is_sender and self.unacked_seq != -1:
                yield self.env.timeout(self.params['slot_time_s'])
                continue
            pkt = yield self.packet_queue.get()
            self.collisions = 0
            if self.is_sender and pkt.ptype == 'DATA':
                self.unacked_seq = pkt.seq_num
            yield self.env.process(self.transmit_retx_loop(pkt))

    def transmit_retx_loop(self, pkt):
        while True:
            is_reliable = (self.is_sender and pkt.ptype == 'DATA')
            tx_proc = self.env.process(self.csma_cd_transmit(pkt))
            if not is_reliable:
                yield tx_proc
                return
            self.retx_proc = self.env.timeout(
                AckSimConfig.RETRANSMISSION_TIMEOUT_S)
            res = yield tx_proc | self.retx_proc
            if tx_proc in res:
                return
            self.stats['timeouts'] += 1
            self.collisions = 0
            if not tx_proc.triggered:
                tx_proc.interrupt()

    def csma_cd_transmit(self, pkt):
        tx_time = self.params['data_tx_time_s'] if pkt.ptype == 'DATA' else self.params['ack_tx_time_s']
        try:
            while True:
                if not self.ether.is_busy():
                    if self.viz:
                        self.viz.update_station_state(self.id, 'transmitting')
                    self.ether.transmitting_stations[self.id] = (
                        pkt, self.env.now)
                    yield self.env.timeout(self.params['propagation_delay_s'])
                    if self.ether.has_collision():
                        if self.viz:
                            self.viz.update_station_state(self.id, 'collision')
                        del self.ether.transmitting_stations[self.id]
                        yield self.env.process(self.handle_collision())
                        return
                    yield self.env.timeout(tx_time - self.params['propagation_delay_s'])
                    del self.ether.transmitting_stations[self.id]
                    self.ether.broadcast(self.id, pkt)
                    if self.viz:
                        self.viz.update_station_state(self.id, 'idle')
                        return
                else:
                    if self.viz:
                        self.viz.update_station_state(self.id, 'deferring')
                    yield self.env.timeout(self.params['slot_time_s'])
        except simpy.Interrupt:
            if self.id in self.ether.transmitting_stations:
                del self.ether.transmitting_stations[self.id]

    def handle_collision(self):
        self.stats['collisions'] += 1
        self.collisions += 1
        self.ether.is_jammed = True
        if self.viz:
            self.viz.trigger_jam()
        yield self.env.timeout(self.params['jam_tx_time_s'])
        self.ether.is_jammed = False
        slots = random.randint(0, (2**min(self.collisions, 10))-1)
        if self.viz:
            self.viz.update_station_state(self.id, 'backing off')
        if slots > 0:
            yield self.env.timeout(slots * self.params['slot_time_s'])


class AckVisualizer(ContentionVisualizer):
    def __init__(self, num_stations, protocol_name):
        super().__init__(num_stations, protocol_name)
        self.screen = pygame.display.set_mode(
            (AckSimConfig.SCREEN_WIDTH, AckSimConfig.SCREEN_HEIGHT))
        pygame.display.set_caption(
            f'Daedaelus Acknowledged Protocol: {protocol_name}')
        self.small_font = pygame.font.Font(None, 18)

    def draw(self, env, ether):
        self.screen.fill((30, 10, 20))
        y, col = AckSimConfig.SCREEN_HEIGHT//2, AckSimConfig.IDLE_COLOR
        if ether.is_jammed or self.jam_animation > 0:
            col, self.jam_animation = AckSimConfig.JAM_COLOR, self.jam_animation - 1
        elif ether.has_collision():
            col = AckSimConfig.COLLISION_COLOR
        elif ether.is_busy():
            col = (100, 255, 100)
        pygame.draw.line(self.screen, col, (50, y),
                         (AckSimConfig.SCREEN_WIDTH-50, y), 3)
        for i, pos in self.station_positions.items():
            s = self.station_states[i]
            pygame.draw.circle(
                self.screen, AckSimConfig.STATION_COLOR, pos, 20)
            pygame.draw.circle(self.screen, s['color'], pos, 15)
            pygame.draw.line(
                self.screen, AckSimConfig.STATION_COLOR, pos, (pos[0], pos[1]-20), 2)
            id_txt, state_txt = self.font.render(
                f"S{i}", True, (255, 255, 255)), self.font.render(s['state'], True, s['color'])
            self.screen.blit(id_txt, (pos[0]-id_txt.get_width()//2, pos[1]+25))
            self.screen.blit(
                state_txt, (pos[0]-state_txt.get_width()//2, pos[1]+45))
        for sid, (pkt, start) in ether.transmitting_stations.items():
            x0 = self.station_positions[sid][0]
            prog = min((env.now-start)*AckSimConfig.PROPAGATION_SPEED_M_S /
                       AckSimConfig.ETHER_LENGTH_M, 1.0)
            w = prog * (AckSimConfig.SCREEN_WIDTH - 100)
            h = AckSimConfig.PACKET_HEIGHT if pkt.ptype == 'DATA' else AckSimConfig.PACKET_HEIGHT - 5
            rect = pygame.Rect(x0 - w/2, y - h/2, w, h)
            pygame.draw.rect(self.screen, pkt.color, rect, border_radius=3)
            info = f"{pkt.ptype} " + \
                (f"S:{pkt.seq_num}" if pkt.ptype ==
                 'DATA' else f"A:{pkt.ack_num}")
            info_surf = self.small_font.render(info, True, (0, 0, 0))
            self.screen.blit(info_surf, (rect.centerx-info_surf.get_width() //
                             2, rect.centery-info_surf.get_height()//2))
        info_txt = self.font.render(
            f"Time: {env.now:.4f}s", True, (255, 255, 255))
        self.screen.blit(info_txt, (10, 10))
        pygame.display.flip()
        self.frames.append(pygame.surfarray.array3d(
            self.screen).transpose((1, 0, 2)))

# --- Main Script & Visualization Logic ---


def run_acknowledged_simulation(params, output_filename):
    """Runs the acknowledged protocol simulation and saves a GIF."""
    random.seed(AckSimConfig.RANDOM_SEED)
    p = AckSimConfig.get_params()
    num_stations = params.get("num_nodes", 5)
    p.update({'num_stations': num_stations, 'sender_id': 0,
             'receiver_id': num_stations - 1})
    stats = collections.defaultdict(int)
    env = simpy.Environment()
    ether = AckEther(env)
    for i in range(p['num_stations']):
        ether.pipes[i] = simpy.Store(env)
    viz = AckVisualizer(p['num_stations'], params.get(
        "protocol", "Acknowledged Proto"))
    stations = [AckStation(env, i, ether, p, stats, viz)
                for i in range(p['num_stations'])]
    while stats['acks_received'] < AckSimConfig.TOTAL_DATA_PACKETS and env.now < AckSimConfig.SIM_DURATION_S:
        env.run(until=env.now + (1/60.0))
        viz.draw(env, ether)
    viz.save_gif(output_filename, fps=30)
    print(f"   -> Acknowledged protocol GIF saved to: {output_filename}")


def run_contention_simulation(params, output_filename):
    """Runs the basic contention simulation and saves a GIF."""
    random.seed(ContentionConfig.RANDOM_SEED)
    sim_params = {
        'propagation_delay_s': ContentionConfig.ETHER_LENGTH_M / ContentionConfig.PROPAGATION_SPEED_M_S,
        'mean_arrival_s': 1.0 / params.get("arrival_rate", 10.0),
        'packet_tx_time_s': params.get("data_size", 1024) * 8 / params.get("bandwidth_bps", 1e7),
        'jam_tx_time_s': ContentionConfig.JAM_SIGNAL_BITS / params.get("bandwidth_bps", 1e7)
    }
    sim_params['slot_time_s'] = 2 * sim_params['propagation_delay_s']
    env = simpy.Environment()
    ether = ContentionEther(env)
    num_stations = params.get("num_nodes", 10)
    viz = ContentionVisualizer(num_stations, params.get("protocol", "CSMA/CD"))
    stations = [ContentionStation(env, i, ether, sim_params, viz)
                for i in range(num_stations)]
    time_step = 1/60.0
    while env.now < ContentionConfig.SIM_DURATION_S:
        env.run(until=env.now + time_step)
        viz.draw(env, ether)
    viz.save_gif(output_filename, fps=30)
    print(f"   -> Contention GIF saved to: {output_filename}")


def load_and_parse_logs(log_path):
    log_data = []
    try:
        with open(log_path, 'r') as f:
            file_content = f.read()
            decoder = json.JSONDecoder()
            pos = 0
            while pos < len(file_content.strip()):
                obj, end_pos = decoder.raw_decode(file_content, pos)
                log_data.extend(obj if isinstance(obj, list) else [obj])
                pos = end_pos
                while pos < len(file_content) and file_content[pos].isspace():
                    pos += 1
    except Exception as e:
        print(f"Error parsing {log_path}: {e}")
        return None
    sim_params = next((item.get("params", {}) for item in log_data if isinstance(
        item, dict) and item.get("event") == "simulation_start"), {})
    protocol_name = next((item.get("protocol", "Unknown") for item in log_data if isinstance(
        item, dict) and item.get("event") == "simulation_start"), "Unknown")
    sim_params["protocol"] = protocol_name
    tx_events, intervals, node_stats, active_transmissions, packet_timeline_events = defaultdict(
        dict), [], defaultdict(lambda: {'success': 0, 'failure': 0}), [], []
    for event in log_data:
        if not isinstance(event, dict):
            continue
        event_type, pkt_id, node_id, time = event.get("event"), event.get(
            "pkt_id"), event.get("src"), event.get("time")
        if event_type == "start_tx":
            if pkt_id:
                tx_events[pkt_id].update(
                    {'start': time, 'src': node_id, 'data': event})
            active_transmissions.append((time, 1))
        elif event_type == "end_tx" and pkt_id and 'start' in tx_events[pkt_id]:
            start_time, src_node, start_data = tx_events[pkt_id]['start'], tx_events[pkt_id].get(
                'src'), tx_events[pkt_id].get('data', {})
            duration, success = time - start_time, event.get("success", False)
            if src_node:
                intervals.append((src_node, start_time, duration, success))
                node_stats[src_node]['success' if success else 'failure'] += 1
            packet_timeline_events.append(({"src": src_node, "dst": start_data.get("dst"), "type": start_data.get("type", "PKT"), "seq": start_data.get(
                "seq"), "ack": start_data.get("ack"), "color": start_data.get("color", "#5E81AC")}, start_time, duration, success))
            del tx_events[pkt_id]
            active_transmissions.append((time, -1))
    return {"protocol_name": protocol_name, "sim_params": sim_params, "active_transmissions": sorted(active_transmissions), "intervals": intervals, "node_stats": node_stats, "packet_timeline": packet_timeline_events}


def create_static_visualizations(data, log_filename):
    if not data or not any([data['active_transmissions'], data['intervals'], data['node_stats'], data['packet_timeline']]):
        return None
    protocol_name = data['protocol_name']
    fig, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(5, 1, figsize=(16, 22),
                                                  sharex=True, gridspec_kw={'height_ratios': [1, 2, 1, 2, 2]})
    fig.suptitle(
        f'Daedaelus Simulation Analysis: {protocol_name}\nLog File: {os.path.basename(log_filename)}', fontsize=16)
    if data['active_transmissions']:
        times, deltas = zip(*data['active_transmissions'])
        ax1.step(times, np.cumsum(deltas), where='post', color='#5E81AC')
    ax1.set_title("Medium Contention Timeline")
    ax1.set_ylabel("Active Transmissions")
    ax1.grid(True, linestyle='--', alpha=0.6)
    if data['intervals']:
        nodes = sorted(list(set([i[0] for i in data['intervals']])))
        node_map = {name: i for i, name in enumerate(nodes)}
        for node, start, dur, ok in data['intervals']:
            if node in node_map:
                ax2.broken_barh([(start, dur)], (node_map[node] - 0.4, 0.8),
                                facecolors='#A3BE8C' if ok else '#BF616A')
        if nodes:
            ax2.set_yticks(range(len(nodes)))
            ax2.set_yticklabels(nodes)
            ax2.set_ylim(-0.5, len(nodes) - 0.5)
    ax2.set_title("Per-Node Transmission Events")
    ax2.set_ylabel("Node ID")
    ax2.grid(True, axis='x', linestyle='--', alpha=0.6)
    if data['node_stats']:
        names = sorted(data['node_stats'].keys())
        x = np.arange(len(names))
        ax3.bar(x - 0.2, [data['node_stats'][n]['success']
                for n in names], 0.4, label='Success', color='#A3BE8C')
        ax3.bar(x + 0.2, [data['node_stats'][n]['failure']
                for n in names], 0.4, label='Failure', color='#BF616A')
        ax3.set_xticks(x)
        ax3.set_xticklabels(names, rotation=45, ha="right")
    ax3.set_title("Per-Node Transmission Outcomes")
    ax3.set_ylabel("Packet Count")
    ax3.legend()
    ax3.grid(True, axis='y', linestyle='--', alpha=0.6)
    lanes = sorted(list(set(f"{e['src']}->{e['dst']}" for e, _,
                   _, _ in data['packet_timeline'] if e['src'] and e['dst'])))
    lane_map = {name: i for i, name in enumerate(lanes)}
    for ax, title, use_pkt_color in [(ax4, "Step-by-Step Daedaelus Token Timeline", True), (ax5, "Step-by-Step TCP-Style Packet Timeline", False)]:
        if data['packet_timeline']:
            for pkt_info, start, dur, ok in data['packet_timeline']:
                direction = f"{pkt_info['src']}->{pkt_info['dst']}"
                if direction in lane_map:
                    color = (pkt_info['color'] if use_pkt_color and ok else (
                        '#A3BE8C' if ok else '#BF616A'))
                    ax.broken_barh([(start, dur)], (lane_map[direction] -
                                   0.3, 0.6), facecolors=color, edgecolor='k', lw=0.5)
                    label = f"{pkt_info['type']}[{pkt_info.get('seq') if pkt_info.get('seq') is not None else pkt_info.get('ack', '')}]"
                    ax.text(start + dur/2, lane_map[direction], label, ha='center', va='center',
                            color='w' if not use_pkt_color else 'k', fontsize=8, weight='bold')
            if lanes:
                ax.set_yticks(range(len(lanes)))
                ax.set_yticklabels(lanes)
                ax.set_ylim(-0.5, len(lanes) - 0.5)
        ax.set_title(title)
        ax.set_ylabel("Communication Lane")
        ax.grid(True, linestyle='--', alpha=0.6)
    ax5.set_xlabel("Time (seconds)")
    for ax in [ax1, ax2, ax3, ax4, ax5]:
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
    plt.tight_layout(rect=[0, 0.03, 1, 0.96])
    return fig

def main():
    """Main execution function to find, visualize, and save all logs and GIFs."""
    os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "1"
    parser = argparse.ArgumentParser(
        description="Daedaelus Log Visualizer", formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("log_directory", nargs='?',
                        default="Logs", help="Path to the log directory.")
    args = parser.parse_args()

    log_dir, plot_root_dir = args.log_directory, "plots"
    if not os.path.isdir(log_dir):
        return print(f"Error: Log directory not found at '{log_dir}'")
    found_logs = [os.path.join(r, f) for r, _, files in os.walk(
        log_dir) for f in files if f.endswith(".json")]
    if not found_logs:
        return print(f"No .json logs found in '{log_dir}'.")
    print(f"Found {len(found_logs)} log files. Generating plots and GIFs...")
    os.makedirs(plot_root_dir, exist_ok=True)

    for log_path in found_logs:
        print(f"\n--- Processing: {log_path} ---")
        parsed_data = load_and_parse_logs(log_path)
        if parsed_data:
            relative_path = os.path.relpath(log_path, log_dir)
            plot_dir = os.path.join(
                plot_root_dir, os.path.dirname(relative_path))
            os.makedirs(plot_dir, exist_ok=True)
            base_name = os.path.basename(relative_path).replace('.json', '')
            fig = create_static_visualizations(parsed_data, log_path)
            if fig:
                plot_filename = os.path.join(plot_dir, f"plot_{base_name}.png")
                print(f"   -> Saving static plot to: {plot_filename}")
                fig.savefig(plot_filename, bbox_inches='tight', dpi=150)
                plt.close(fig)
            sim_params = parsed_data.get("sim_params", {})
            if sim_params:
                proto = sim_params.get("protocol", "").lower()
                if 'aloha' in proto or 'metcalfe' in proto or 'contention' in proto:
                    gif_filename = os.path.join(
                        plot_dir, f"contention_{base_name}.gif")
                    try:
                        run_contention_simulation(sim_params, gif_filename)
                    except Exception as e:
                        print(f"   -> FAILED contention GIF: {e}")
                        pygame.quit()
                if 'tcp' in proto or 'duplex' in proto or 'fibre' in proto or 'daedaelus' in proto:
                    gif_filename = os.path.join(
                        plot_dir, f"acknowledged_{base_name}.gif")
                    try:
                        run_acknowledged_simulation(sim_params, gif_filename)
                    except Exception as e:
                        print(f"   -> FAILED acknowledged GIF: {e}")
                        pygame.quit()
    print(
        f"\nAll visualizations have been saved to the '{plot_root_dir}' directory.")

if __name__ == "__main__":
    main()
