#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Daedaelus Log Visualizer - Automated Directory Traversal
---------------------------------------------------------
Creates comprehensive visualizations from all simulation log files found
within a specified directory structure. This script is designed to parse the
JSON logs generated by test_ethernet.py and produce four key plots for each log,
saving each figure to a separate image file.

Usage:
  python log_visualizer.py [path/to/logs/directory]
  If no path is provided, it defaults to searching for a 'Logs' directory
  in the current location.
"""

import json
import argparse
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import os


def load_and_parse_logs(log_path):
    """
    Loads a JSON log file and processes it into data structures for plotting.

    This function is critical for our "Code as Proof" approach. It treats the
    log file as a primary source of truth, extracting the event history needed
    to reconstruct the simulation's behavior.

    Args:
        log_path (str): The path to the simulation log file.

    Returns:
        A dictionary containing the processed data for visualization, or None if
        the file cannot be processed.
    """
    log_data = []
    try:
        with open(log_path, 'r') as f:
            file_content = f.read()
            decoder = json.JSONDecoder()
            pos = 0
            # FIX: The log files appear to be concatenations of multiple JSON arrays.
            # This loop repeatedly decodes JSON objects from the file content
            # until the entire file is consumed, robustly handling the format.
            while pos < len(file_content.strip()):
                obj, end_pos = decoder.raw_decode(file_content, pos)
                if isinstance(obj, list):
                    log_data.extend(obj)
                else:
                    log_data.append(obj)
                pos = end_pos
                # Find the start of the next JSON object
                while pos < len(file_content) and file_content[pos].isspace():
                    pos += 1
    except (json.JSONDecodeError, FileNotFoundError) as e:
        print(f"Error: Could not read or parse log file at {log_path}. {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred processing {log_path}: {e}")
        return None

    # -- The first event in the log contains the simulation parameters. --
    sim_params = next((item for item in log_data if isinstance(item, dict) and item.get(
        "event") == "simulation_start"), {})
    protocol_name = sim_params.get("protocol", "Unknown Protocol")

    tx_events = defaultdict(dict)
    intervals = []
    node_stats = defaultdict(lambda: {'success': 0, 'failure': 0})
    active_transmissions = []
    packet_timeline_events = []

    # -- Each event is a point in the causal history of the system. --
    for event in log_data:
        if not isinstance(event, dict):
            continue

        event_type = event.get("event")
        pkt_id = event.get("pkt_id")
        node_id = event.get("src")
        time = event.get("time")

        if event_type == "start_tx":
            # -- A 'start_tx' event marks the moment a node attempts to impose --
            # -- its state on the medium. In a contended system, this is the --
            # -- beginning of a potential collision. --
            if pkt_id:
                tx_events[pkt_id]['start'] = time
                tx_events[pkt_id]['src'] = node_id
                tx_events[pkt_id]['data'] = event
            active_transmissions.append((time, 1))

        elif event_type == "end_tx":
            # -- An 'end_tx' event is the resolution of a transmission attempt. --
            if pkt_id and 'start' in tx_events[pkt_id]:
                start_time = tx_events[pkt_id]['start']
                duration = time - start_time
                success = event.get("success", False)
                src_node = tx_events[pkt_id].get('src')
                start_data = tx_events[pkt_id].get('data', {})

                if src_node:
                    intervals.append((src_node, start_time, duration, success))
                    if success:
                        node_stats[src_node]['success'] += 1
                    else:
                        node_stats[src_node]['failure'] += 1

                packet_info = {
                    "src": src_node,
                    "dst": start_data.get("dst"),
                    "type": start_data.get("type", "PKT"),
                    "seq": start_data.get("seq"),
                    "ack": start_data.get("ack"),
                    "color": start_data.get("color", "#5E81AC")
                }
                packet_timeline_events.append(
                    (packet_info, start_time, duration, success))

                del tx_events[pkt_id]
            active_transmissions.append((time, -1))

    return {
        "protocol_name": protocol_name,
        "active_transmissions": sorted(active_transmissions),
        "intervals": intervals,
        "node_stats": node_stats,
        "packet_timeline": packet_timeline_events
    }


def create_visualizations(data, log_filename):
    """
    Generates the four core visualizations from the parsed log data and returns
    the figure object.
    """
    if not data:
        print("No data to visualize.")
        return None

    protocol_name = data['protocol_name']
    active_transmissions = data['active_transmissions']
    intervals = data['intervals']
    node_stats = data['node_stats']
    packet_timeline = data['packet_timeline']

    if not any([active_transmissions, intervals, node_stats, packet_timeline]):
        print(
            f"Log file '{log_filename}' for protocol '{protocol_name}' contains no transmission events.")
        return None

    fig, (ax1, ax2, ax3, ax4) = plt.subplots(
        4, 1, figsize=(16, 18), sharex=True, gridspec_kw={'height_ratios': [1, 2, 1, 2]})
    fig.suptitle(
        f'Daedaelus Simulation Analysis: {protocol_name}\nLog File: {os.path.basename(log_filename)}', fontsize=16)

    # -- Plot 1: Medium Contention Timeline --
    if active_transmissions:
        times, deltas = zip(*active_transmissions)
        usage = np.cumsum(deltas)
        ax1.step(times, usage, where='post', color='#5E81AC')
    ax1.set_ylabel("Active Transmissions")
    ax1.set_title("Medium Contention Timeline")
    ax1.grid(True, linestyle='--', alpha=0.6)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)

    # -- Plot 2: Per-Node Transmission Gantt Chart --
    if intervals:
        nodes = sorted(list(set([i[0] for i in intervals])))
        node_map = {name: i for i, name in enumerate(nodes)}

        for node_name, start, dur, ok in intervals:
            y_val = node_map.get(node_name)
            if y_val is not None:
                color = '#A3BE8C' if ok else '#BF616A'
                ax2.broken_barh([(start, dur)], (y_val - 0.4, 0.8),
                                facecolors=color, edgecolor='black', linewidth=0.5)
        if nodes:
            ax2.set_yticks(range(len(nodes)))
            ax2.set_yticklabels(nodes)
            ax2.set_ylim(-0.5, len(nodes) - 0.5)
    ax2.set_ylabel("Node ID")
    ax2.set_title("Per-Node Transmission Events (Green=Success, Red=Failure)")
    ax2.grid(True, axis='x', linestyle='--', alpha=0.6)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)

    # -- Plot 3: Per-Node Success/Failure Counts --
    if node_stats:
        node_names = sorted(node_stats.keys())
        success_counts = [node_stats[n]['success'] for n in node_names]
        failure_counts = [node_stats[n]['failure'] for n in node_names]
        bar_width = 0.4
        x = np.arange(len(node_names))

        ax3.bar(x - bar_width/2, success_counts, bar_width,
                label='Success', color='#A3BE8C')
        ax3.bar(x + bar_width/2, failure_counts, bar_width,
                label='Failure/Collision', color='#BF616A')

        ax3.set_xticks(x)
        ax3.set_xticklabels(node_names, rotation=45, ha="right")
    ax3.set_ylabel("Packet Count")
    ax3.set_title("Per-Node Transmission Outcomes")
    ax3.legend()
    ax3.grid(True, axis='y', linestyle='--', alpha=0.6)
    ax3.spines['top'].set_visible(False)
    ax3.spines['right'].set_visible(False)

    # -- Plot 4: Step-by-Step Packet Timeline --
    if packet_timeline:
        lanes = sorted(list(set(f"{evt['src']}->{evt['dst']}" for evt,
                       _, _, _ in packet_timeline if evt['src'] and evt['dst'])))
        lane_map = {name: i for i, name in enumerate(lanes)}

        for packet_info, start, dur, ok in packet_timeline:
            direction = f"{packet_info['src']}->{packet_info['dst']}"
            y_val = lane_map.get(direction)
            if y_val is not None:
                color = packet_info['color'] if ok else '#BF616A'
                ax4.broken_barh([(start, dur)], (y_val - 0.3, 0.6),
                                facecolors=color, edgecolor='black', linewidth=0.5)
                pkt_type, seq, ack = packet_info['type'], packet_info.get(
                    'seq'), packet_info.get('ack')
                label = f"{pkt_type}[{seq}]" if "DATA" in pkt_type and seq is not None else f"{pkt_type}[{ack}]" if "ACK" in pkt_type and ack is not None else f"{pkt_type}"
                ax4.text(start + dur / 2, y_val, label, ha='center',
                         va='center', color='black', fontsize=8, weight='bold')

        if lanes:
            ax4.set_yticks(range(len(lanes)))
            ax4.set_yticklabels(lanes)
            ax4.set_ylim(-0.5, len(lanes) - 0.5)
    ax4.set_xlabel("Time (seconds)")
    ax4.set_ylabel("Communication Lane")
    ax4.set_title("Step-by-Step Packet Timeline")
    ax4.grid(True, linestyle='--', alpha=0.6)
    ax4.spines['top'].set_visible(False)
    ax4.spines['right'].set_visible(False)

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    return fig


def main():
    """Main execution function to find, visualize, and save all logs."""
    parser = argparse.ArgumentParser(
        description="Daedaelus Log Visualizer: Automatically finds and visualizes all simulation logs in a directory.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "log_directory", nargs='?', default="Logs",
        help="Path to the root directory containing protocol log folders. Defaults to './Logs'."
    )
    args = parser.parse_args()

    log_dir = args.log_directory
    plot_root_dir = "plots"
    if not os.path.isdir(log_dir):
        print(f"Error: Log directory not found at '{log_dir}'")
        return

    found_logs = [os.path.join(root, filename) for root, _, files in os.walk(
        log_dir) for filename in files if filename.endswith(".json")]

    if not found_logs:
        print(
            f"No .json log files found in '{log_dir}' or its subdirectories.")
        return

    print(f"Found {len(found_logs)} log files to visualize...")
    os.makedirs(plot_root_dir, exist_ok=True)

    for log_path in found_logs:
        print(f"\n--- Processing: {log_path} ---")
        parsed_data = load_and_parse_logs(log_path)
        if parsed_data:
            fig = create_visualizations(parsed_data, log_path)
            if fig:
                # Create a corresponding output path for the plot
                relative_log_path = os.path.relpath(log_path, log_dir)
                plot_dir = os.path.join(
                    plot_root_dir, os.path.dirname(relative_log_path))
                os.makedirs(plot_dir, exist_ok=True)

                base_log_name = os.path.basename(
                    relative_log_path).replace('.json', '.png')
                plot_filename = os.path.join(plot_dir, f"plot_{base_log_name}")

                print(f"   -> Saving visualization to: {plot_filename}")
                fig.savefig(plot_filename, bbox_inches='tight', dpi=150)
                plt.close(fig)  # Close the figure to free up memory

    print(
        f"\nAll visualizations have been saved to the '{plot_root_dir}' directory.")


if __name__ == "__main__":
    main()
